name: Release

on:
  push:
    branches: 
      - main

jobs:
  build:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      
      - name: Fetch dependencies
        run: go get .
      
      - name: Build RESTc
        run: go build -o bin/restc cmd/restc.go
      
      - name: Build RESTc GIN plugin
        run: go build -o bin/restc-gin plugins/gin/cmd/restc-gin.go

      - name: Set short commit env
        run: echo "COMMIT_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      - name: Create release and upload files
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh release create v0.0.0-${{env.COMMIT_SHORT}} --target ${{github.sha}} bin/restc bin/restc-gin